version: '2'
services:
  gateway:
    container_name: monorepo-gateway
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    ports:
      - '3002:3002'
      - '5870:5870'
    volumes:
      - .:/src:cached
  nest-docker-aws:
    container_name: monorepo-nest-docker-aws
    build:
      context: .
      dockerfile: ./apps/nest-docker-aws/Dockerfile
    ports:
      - '3003:3003'
      - "5880:5880"
    volumes:
      - .:/src:cached
  tasks:
    container_name: monorepo-tasks
    build:
      context: .
      dockerfile: ./apps/tasks/Dockerfile
    ports:
      - '3001:3001'
      - "5890:5890"
    volumes:
      - .:/src:cached